name: Deployment

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 15.x
        uses: actions/setup-node@v3
        with:
          node-version: 15.x


      - name: Install dependencies
        run: npm ci

      - name: Set identity email
        run:  git config --global user.email "wandergonzalez0@hotmail.com"

      - name: Set identity name
        run:  git config --global user.name "Wander Gonzalez"

      - name: Build
        run: npm run deploy
