name: Deployment

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 15.x
        uses: actions/setup-node@v3
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: |
          npm run build
          npx gh-pages -d build --user "wandergithub wandergonzalez0@hotmail.com "
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.PAT }}